# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

In [187]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura em metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [188]:
lista_de_alturas = list(range(170, 190, 5))
print(f'lista_de_alturas {lista_de_alturas}')

# seu código aqui
altura_em_centimetros = np.array(lista_de_alturas)
print (f'array altura_em_centimetros {altura_em_centimetros}')
print (f'tipo array altura_em_centimetros {type(altura_em_centimetros)}')

lista_de_alturas [170, 175, 180, 185]
array altura_em_centimetros [170 175 180 185]
tipo array altura_em_centimetros <class 'numpy.ndarray'>


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [189]:
lista_pesos = [70, 75, 80, 85]
# seu código aqui

#criando ndarray chamado pesos
pesos = np.array(lista_pesos)
print(f'array pesos {pesos}')



array pesos [70 75 80 85]


In [190]:
# calcule o IMC dessas pessoas

#imc = peso/(altura * altura)

imc = pesos / (altura_em_centimetros ** 2)
print(f'imc {imc}')

imc [0.00242215 0.00244898 0.00246914 0.00248356]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [191]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
#i) transforme essa lista em um ndarray
nd_financeiros = np.array(dados_financeiros)
print (f'nd_financeiros {nd_financeiros}')

nd_financeiros [[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [192]:
# ii) 
# metodo .transpose
nd_financeiros_t = np.transpose(nd_financeiros)
print(f'nd_financeiros {nd_financeiros_t}')

#segunda linha do array, depois a segunda coluna.
print(f'segunda linha do array nd_financeiros_t {nd_financeiros_t[1]}')
print(f'segunda coluna do array nd_financeiros_t {nd_financeiros_t[:,1]}')

nd_financeiros [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]
segunda linha do array nd_financeiros_t [2500 2500 5500]
segunda coluna do array nd_financeiros_t [1000 2500 3000 5000]


In [193]:
# iii) Calcule o endividamento total
endividamento_total = (nd_financeiros_t[:,0] + nd_financeiros_t[:,1])/nd_financeiros_t[:,2]

print(f'endividamento_total {endividamento_total}')      

endividamento_total [0.66666667 0.90909091 0.57142857 0.9375    ]


In [194]:
# iv) corrigindo um valor específico
nd_financeiros_t[2,2] = 10000 
print (f'nd_financeiros_t  {nd_financeiros_t}')

#calculando o endividamento total após a correção
endividamento_total = (nd_financeiros_t[:,0] + nd_financeiros_t[:,1])/nd_financeiros_t[:,2]

print(f'endividamento_total {endividamento_total}')   

nd_financeiros_t  [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000 10000]
 [10000  5000 16000]]
endividamento_total [0.66666667 0.90909091 0.4        0.9375    ]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [215]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(12345) ;
poi =  np.array(random.sample(range(0,1000000), k=10000))
#poi = np.array([10,0,0,15])

print (f'poi {poi}')


poi [727112 728339 217473 ... 131947 470360 385640]


In [216]:
# i) crie o objeto bool_zero através do operador ==
bool_zero = poi == 0
print (f'bool_zero {bool_zero}')

bool_zero [False False False ... False False False]


In [217]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)
soma = bool_zero.sum() 
print(f'soma {soma}')

soma 0


In [218]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

print (f'bool_zero {bool_zero}')

#invertendo o array bool
bool_nao_zero = np.invert(bool_zero)

print (f'bool_nao_zero {bool_nao_zero}')

#utilizando a indexação booleana
poi_nao_zero = poi[bool_nao_zero]
print (f'poi_nao_zero {poi_nao_zero}')

bool_zero [False False False ... False False False]
bool_nao_zero [ True  True  True ...  True  True  True]
poi_nao_zero [727112 728339 217473 ... 131947 470360 385640]
